services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - cd gentoo_emerge
  - docker build --network host -f Dockerfile -t gentoo_emerge_bionic .
  - cd ../ros_base
  - docker build --network host -f Dockerfile -t sbre_robot_ros_melodic_gentoo_prefix .